# Generated by Django 5.1.5 on 2025-02-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bookLists', models.JSONField(default=list, help_text='A list of the booklists, each booklist containing book ids')),
            ],
        ),
    ]
