# Generated by Django 5.1.5 on 2025-02-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bookLists',
            new_name='readingLists',
        ),
    ]
