# Generated by Django 5.1.5 on 2025-02-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='This is a great book!', max_length=400),
        ),
    ]
